### ISSUE TITLE
Support for Chrome 79 (Puppeteer 2.0.0)

### ISSUE THREAD

**Issue by stanolacko** [rialto-php/puphpeteer#71]
What is current devepoling status for importement support for Chrome 79 (Puppeteer 2.0.0)?

**Comment by spekulatius** [comment]
Here are some thoughts on what should be considered before/as part of upgrading to the latest Chrome version:

  - update version in package.json
  - check the [Puppeteer release notes](https://github.com/puppeteer/puppeteer/releases) since the currently used version and add missing resources accordingly and update aliases, if changed.
  - confirm tests and Travis working correctly

The list isn't conclusive and might change.

**Comment by stanolacko** [comment]
Well I thing this needs new maintainer, because @nesk is not involved in this project anymore.
Somebody with node.js skills is required to maintain this project

**Comment by spekulatius** [comment]
Hey @stanolacko 

I've had a long chat with @nesk about the project and going to help out to keep it going. Stay tuned!

Cheers,
Peter

**Comment by spekulatius** [comment]
See https://github.com/puppeteer/puppeteer/blob/main/docs/api.md for overview of the API

**Comment by stanolacko** [comment]
Cool, one of the best news today.
So good luck and waiting for new release ;-)

**Comment by spekulatius** [comment]
Thanks, it's a piece of work. Been working on adding more tests so we can be more sure it's actually working as expected.

**Comment by nesk** [comment]
Closing since Puppeteer 5 is coming real soon with the 2.0.0 release.
